# Generated by Django 4.0.6 on 2022-07-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original_key',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
    ]
