# Generated by Django 4.0.6 on 2022-07-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_song_arranger_song_author_song_links_song_lyrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='arranger',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='song',
            name='links',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='song',
            name='musicians',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='song',
            name='notes',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='song',
            name='original_key',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='producer',
            field=models.CharField(default='', max_length=150),
        ),
    ]
