# Generated by Django 4.0.6 on 2022-07-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_musician_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician_photo',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.musician'),
        ),
    ]
