# Generated by Django 4.0.6 on 2022-07-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_musician_photo_musician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician_photo',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
