# Generated by Django 4.0.6 on 2022-07-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_musician_photo_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musician_Photo',
            new_name='Photo',
        ),
    ]
